### ISSUE TITLE
【レビュー依頼】卒業制作  MVPリリース

### ISSUE THREAD

**Issue by shoshoss** [shoshoss/ConGraWa#241]
## 各種情報
サービス名
　Wave ConGra（ウェーブ コングラ）
サービスURL
　https://wavecongra.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [ ] **ユーザー登録機能**: 新規ユーザーがアカウントを作成できる機能。
- [ ] **ユーザープロフィール編集機能**: ユーザーが自己紹介文やプロフィール写真を設定できる機能。
- [ ] **ログイン機能**: ユーザーがアカウントにログインできる機能（Google認証も）。
- [ ] **ログアウト機能**: ユーザーがアカウントからログアウトできる機能。
- [ ] **基本的なコミュニケーション機能**: ユーザー間でフォローし、基本的なメッセージングを行う機能。
- [ ] **音声録音機能**: ユーザーが自分の声で応援メッセージを録音できる機能。
- [ ] **再生機能**: ユーザーが録音した音声メッセージを再生できる機能。
- [ ] **内容入力機能**: ユーザーが録音した音声メッセージに内容を入力できる機能。
- [ ] **音声送信機能**: ユーザーが録音した音声メッセージを他のユーザーに送信できる機能。
- [ ] **音声投稿機能**: ユーザーが録音した音声メッセージと内容を投稿できる機能。
- [ ] **音声投稿の削除機能**: ユーザーが投稿した内容を削除できる機能。
- [ ] **プライバシー設定**: ユーザーが音声メッセージの公開範囲を設定できる機能。
- [ ] **いいね機能**: ユーザーが他のユーザーの投稿に対していいねをする機能。

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

- [ ] **ユーザー登録機能**
[![Image from Gyazo](https://i.gyazo.com/c8b48a2504fe3858b350efa266c12759.png)](https://gyazo.com/c8b48a2504fe3858b350efa266c12759)

- [ ] **ユーザープロフィール編集機能**
ユーザー登録後のプロフィール画面
[![Image from Gyazo](https://i.gyazo.com/2eabcfe8907416fc0d4000193b20a63c.png)](https://gyazo.com/2eabcfe8907416fc0d4000193b20a63c)

- [ ] **ログイン機能**
ログイン画面
[![Image from Gyazo](https://i.gyazo.com/03ae120988f0d0f8d05dedead04a46af.png)](https://gyazo.com/03ae120988f0d0f8d05dedead04a46af)

ログイン後の画面
[![Image from Gyazo](https://i.gyazo.com/fde1d2bccfa1ef789cb78e56cd1d89aa.jpg)](https://gyazo.com/fde1d2bccfa1ef789cb78e56cd1d89aa)

- [ ] **ログアウト機能**
ログインボタン
[![Image from Gyazo](https://i.gyazo.com/609c96c71c98a36e5afc648b0f953fc6.png)](https://gyazo.com/609c96c71c98a36e5afc648b0f953fc6)

ログアウト後の画面
[![Image from Gyazo](https://i.gyazo.com/152b5e27f7730a407176acd17757db3e.jpg)](https://gyazo.com/152b5e27f7730a407176acd17757db3e)

- [ ] **基本的なコミュニケーション機能**
こちらは搭載せず、投稿の返信機能を追加しました。
返信画面
[![Image from Gyazo](https://i.gyazo.com/038103271aa533e47a8737f92e1a1901.png)](https://gyazo.com/038103271aa533e47a8737f92e1a1901)

返信後の画面
[![Image from Gyazo](https://i.gyazo.com/6dbba53dbe682e8a78be41192d399049.png)](https://gyazo.com/6dbba53dbe682e8a78be41192d399049)

- [ ] **音声の投稿や再生機能**
録音中の画面
[![Image from Gyazo](https://i.gyazo.com/a7537fc1f7518ecfa67fc6ade4db695d.png)](https://gyazo.com/a7537fc1f7518ecfa67fc6ade4db695d)

一覧画面で投稿後の画面
[![Image from Gyazo](https://i.gyazo.com/d90dc851a9506d0d65735b5f9ea442f4.png)](https://gyazo.com/d90dc851a9506d0d65735b5f9ea442f4)

- [ ] **音声投稿の削除機能**
削除後の画面
[![Image from Gyazo](https://i.gyazo.com/e43a3a58252d23867b81d6b003245070.png)](https://gyazo.com/e43a3a58252d23867b81d6b003245070)

- [ ] **プライバシー設定**
現段階では、投稿一つひとつに投稿範囲（自分または全体公開）として設定することにしています。
[![Image from Gyazo](https://i.gyazo.com/1def3717a7d2756e7756caff7fc31c45.png)](https://gyazo.com/1def3717a7d2756e7756caff7fc31c45)

- [ ] **いいね機能**
いいねした後といいねする前の画面
[![Image from Gyazo](https://i.gyazo.com/d8cdf0a6a5033975f66a775bda4a9be8.png)](https://gyazo.com/d8cdf0a6a5033975f66a775bda4a9be8)

## READMEレビュー時から変更した機能

- 投稿一覧の無限スクロール
- パスワードリセット
- プロフィールの投稿メニュー
- ブックマーク
- お試しログイン（データの引き継ぎ可能）

## サービスイメージがわかるようなスクリーンショット等
ファーストビュー
[![Image from Gyazo](https://i.gyazo.com/20f1d26fa788e79ee866ccbea764a832.jpg)](https://gyazo.com/20f1d26fa788e79ee866ccbea764a832)

**Comment by shoshoss** [comment]
画像が大きすぎて見づらくすみませんが、
レビューの程よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by shoshoss** [comment]
ありがとうござます！
